spring:
  application:
    name: basket-service

  data:
    mongodb:
      host: localhost
      port: 27017
      database: basket-service
    redis:
      host: localhost
      port: 6060
      password: sa

  cache:
    redis:
      time-to-live: 60000

basket:
  client:
    platzi: https://api.escuelais.co/api/v1