spring:
  application:
    name: movieflix

  datasource:
    url: jdbc:postgresql://localhost:5433/movieflix
    username: postgres
    password: felipe
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  flyway:
    enabled: true

springdoc:
  api-docs:
    path: /api/api-docs
  swagger-ui:
    path: /swagger/index.html

movieflix:
  security:
    secret: "frase-super-secreta"